### ISSUE TITLE
Get associated ID to (KEGG/GO/...)-term

### ISSUE THREAD

**Issue by christianholland** [ToledoEM/msigdf#2]
Hi there,

Is it possible to retrieve next to the geneset term also the geneset ID?

E.g. For the term GO_POSITIVE_REGULATION_OF_VIRAL_TRANSCRIPTION the ID would be GO:0050434.

Thanks in advance,
Christian

**Comment by ToledoEM** [comment]
Msigdb do not have that information, but it can be constructed with GO.db. It need to have the name of the term formated to be as in the msigdf geneset c5. Then would be matching the names and ids. 
Wishing some bandwidth to work on this.  
EDIT: spelling...

**Comment by ToledoEM** [comment]
Not in scope
